# Generated by Django 4.0 on 2021-12-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicatia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='completat',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='creat',
        ),
    ]
